  expression  = [ "(" ]
                ( constraint / expression )
                [ operator ( constraint / expression ) ]
                [ ")" ]
  operator    = ";" / ","
  constraint  = selector [ comparison argument ]
  selector    = 1*( unreserved / pct-encoded )
  comparison  = ( ( "=" 1*ALPHA ) / fiql-delim ) "="
  argument    = 1*arg-char
  arg-char    = unreserved / pct-encoded / fiql-delim / "="
  fiql-delim  = "!" / "$" / "'" / "*" / "+"
  text-arg    = [ "*" ] 1*arg-char [ "*" ]
  date-arg    = dateTime / duration ; as defined in XML Schema Datatypes
  number-arg  = [ "+" / "-" ] 1*DIGIT [ "." 1*DIGIT ]
